// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_m7106a2ydhreEyaNePhuV4syM9J6fs',
    appId: '1:812117274125:web:83973a6f008cd2fad0af44',
    messagingSenderId: '812117274125',
    projectId: 'flash-chat-10471',
    authDomain: 'flash-chat-10471.firebaseapp.com',
    storageBucket: 'flash-chat-10471.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5y0G0d4swGKg5AWUY49EXW3-7d27xG4c',
    appId: '1:812117274125:android:7293241a870a3940d0af44',
    messagingSenderId: '812117274125',
    projectId: 'flash-chat-10471',
    storageBucket: 'flash-chat-10471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBClbIDx93z37R9ExpGHVbFBoUk5A91T9g',
    appId: '1:812117274125:ios:6eaf32da4e96f849d0af44',
    messagingSenderId: '812117274125',
    projectId: 'flash-chat-10471',
    storageBucket: 'flash-chat-10471.appspot.com',
    iosBundleId: 'com.example.firebasechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBClbIDx93z37R9ExpGHVbFBoUk5A91T9g',
    appId: '1:812117274125:ios:6eaf32da4e96f849d0af44',
    messagingSenderId: '812117274125',
    projectId: 'flash-chat-10471',
    storageBucket: 'flash-chat-10471.appspot.com',
    iosBundleId: 'com.example.firebasechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7_m7106a2ydhreEyaNePhuV4syM9J6fs',
    appId: '1:812117274125:web:f6dfb5224f4c7cc2d0af44',
    messagingSenderId: '812117274125',
    projectId: 'flash-chat-10471',
    authDomain: 'flash-chat-10471.firebaseapp.com',
    storageBucket: 'flash-chat-10471.appspot.com',
  );
}
